/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#d0bcff',
        'primary-container': '#8252ec',
        'primary-fixed': '#e9ddff',
        'primary-fixed-dim': '#d0bcff',
        secondary: '#cdbdff',
        'secondary-container': '#4e3b8c',
        'secondary-fixed': '#e8deff',
        'secondary-fixed-dim': '#cdbdff',
        tertiary: '#ffb688',
        'tertiary-container': '#b55800',
        'tertiary-fixed': '#ffdbc7',
        'tertiary-fixed-dim': '#ffb688',
        surface: '#0b1326',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-variant': '#2d3449',
        'surface-tint': '#d0bcff',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#cac3d8',
        'on-primary': '#3c0091',
        'on-primary-container': '#fdf6ff',
        'on-secondary': '#352071',
        'on-secondary-container': '#c0acff',
        'on-tertiary': '#512400',
        'on-tertiary-container': '#fff7f4',
        background: '#0b1326',
        'on-background': '#dae2fd',
        outline: '#948ea1',
        'outline-variant': '#494455',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        'inverse-primary': '#6d3bd7',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '0.75rem',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(to bottom right, #d0bcff, #8252ec)',
        'gradient-text': 'linear-gradient(to right, #d0bcff, #8252ec)',
      },
    },
  },
  plugins: [],
};